# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Hi my name is Amr"
description: > # this means to ignore newlines until "email:"
   My goal is to share my software development knowledge with the world

email: amr.raafat.omran@gmail.com
#blog logo
logo: "/assets/images/ao_logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Amr Omran'
author: 'Amr Omran'
author_image: "/assets/images/author.JPEG"

paginate:	5

url: "https://amromran89.github.io"
baseurl: "/swift-tutorials" 

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/amr-omran-61a166341/
    desc:	Share on LinkedIn
    share_url:	https://www.linkedin.com/sharing/share-offsite/?
    share_title:	null
    share_link:	url=

  - icon:	copy
    url:	#
    desc:	Copy link
    share_url:	null
    share_title:	null
    share_link:	null

  - icon:	github
    url:	https://github.com/amrOmran89
    desc:	Fork me on github
    share_url:	null
    share_title:	null
    share_link:	null

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
