# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Hi my name is Amr"
description: > # this means to ignore newlines until "email:"
   My goal is to share my software development knowledge with the world

email: amr.raafat.omran@gmail.com
#blog logo
logo: "/assets/images/ao_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Amr Omran'
author: 'Amr Omran'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://amromran89.github.io"
baseurl: "/swift-tutorials" 

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/amrOmran89
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
